version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
     - site-network

  php:
    image: wordpress:php7.1-fpm
    depends_on:
      - mysql
    restart: always
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    networks:
     - site-network

  nginx:
    image: nginx:latest
    depends_on:
      - php
    restart: always
    environment:
      VIRTUAL_HOST: site1.test
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
     - site-network

networks:
  site-network:
    external:
      name: custom-network
