version: '3'

services:
  mail:
    image: mailhog/mailhog
    restart: always
    command: ["-invite-jim=false"]
    environment:
      - VIRTUAL_HOST=mail.site1.test
      - VIRTUAL_PORT=8025
    networks:
     - site-network

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
     - site-network

  php:
    image: rtcamp/wordpress
    depends_on:
      - mysql
    restart: always
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    environment:
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    networks:
     - site-network

  nginx:
    image: nginx:latest
    depends_on:
      - php
    restart: always
    environment:
      - VIRTUAL_HOST=site1.test
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"
    networks:
     - site-network

networks:
  site-network:
    external:
      name: custom-network
